# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "timpietrusky"
license = "MIT"
licenselink = "https://github.com/TimPietrusky/timpietrusky.com/blob/master/LICENSE.md"
description = "Personal Portfolio theme."
homepage = "https://timpietrusky.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Tim Pietrusky"
  homepage = "https://timpietrusky.com"
